fixed error when rule is null
$validator.getRule can return null and without this check this error would be raised:
    TypeError: Cannot read property 'init' of null
    at http://localhost:9000/bower_components/angular-validator/dist/angular-validator.js:141:32